### ISSUE TITLE
Can't parse Major.Micro.Minor.Build i.e. Microsoft style

### ISSUE THREAD

**Issue by charlesritchea** [zafarkhaja/jsemver#40] opened 2017-06-06 16:12 UTC
I know Microsoft's 1.2.3.4 isn't the same as Semantic versioning, but I would expect this library to at least be able to parse the first 3 in the tuple and put the 4th somewhere appropriate. Right now if you try to parse this it throws an exception.

**Comment by stchar** [comment] 2017-12-11 10:53
@novaterata,

I think this functionality should be implemented as a dedicated library.
However, in .NET world java is not a popular environment for CI/CD so i'm not sure that there is a demand.

**Comment by zafarkhaja** [comment] 2023-04-15 05:34
This is a duplicate of #15.

**Comment by zafarkhaja** [comment] 2024-01-14 14:34
Closing this issue in favor of #69, the progress can be followed from there.

**Closed by zafarkhaja** 2024-01-14 14:34 UTC
Labels: status/duplicate, type/feature-request
