### ISSUE TITLE
Support for npm semver X-Ranges 1.2.x 1.X 1.2.

### ISSUE THREAD

**Issue by morad3741** [zafarkhaja/jsemver#53] opened 2019-08-18 09:03 UTC
Hi, i'm using version 0.9.0 and im receiving unexpectedTokenException when trying to use:   
Version v1 = Version.valueOf("5.10.1");
System.out.println(v1.satisfies("5.x.0"));

https://docs.npmjs.com/misc/semver#x-ranges-12x-1x-12-

**Comment by zafarkhaja** [comment] 2023-04-15 07:02
Duplicate of #45.

**Comment by zafarkhaja** [comment] 2024-01-14 14:54
Closing this issue in favor of #70, the progress can be followed from there.

**Comment by zafarkhaja** [comment] 2024-01-14 14:54
Closing this issue in favor of #70, the progress can be followed from there.

**Closed by zafarkhaja** 2024-01-14 14:54 UTC
Labels: status/duplicate, type/feature-request
